apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - ../../../base/coach-service

images:
  - name: ghcr.io/mihaicatalin22/questify-coach-service
    newTag: main-70ad63c

patchesJson6902:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: coach-service
      namespace: default
    path: patch-env.yaml
