apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: questify-frontend-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: questify-frontend }
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: 70 }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quest-service-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: quest-service }
  behavior:
    scaleUp:   { stabilizationWindowSeconds: 0,   policies: [ { type: Percent, value: 100, periodSeconds: 60 } ] }
    scaleDown: { stabilizationWindowSeconds: 300, policies: [ { type: Percent, value: 50,  periodSeconds: 60 } ] }
  metrics:
    - type: Resource
      resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: user-service }
  behavior:
    scaleUp:   { stabilizationWindowSeconds: 0,   policies: [ { type: Percent, value: 100, periodSeconds: 60 } ] }
    scaleDown: { stabilizationWindowSeconds: 300, policies: [ { type: Percent, value: 50,  periodSeconds: 60 } ] }
  metrics:
    - type: Resource
      resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: submission-service-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: submission-service }
  behavior:
    scaleUp:   { stabilizationWindowSeconds: 0,   policies: [ { type: Percent, value: 100, periodSeconds: 60 } ] }
    scaleDown: { stabilizationWindowSeconds: 300, policies: [ { type: Percent, value: 50,  periodSeconds: 60 } ] }
  metrics:
    - type: Resource
      resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: proof-service-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: proof-service }
  behavior:
    scaleUp:   { stabilizationWindowSeconds: 0,   policies: [ { type: Percent, value: 100, periodSeconds: 60 } ] }
    scaleDown: { stabilizationWindowSeconds: 300, policies: [ { type: Percent, value: 50,  periodSeconds: 60 } ] }
  metrics:
    - type: Resource
      resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }
