apiVersion: v1
kind: Service
metadata:
  name: streak-service
  labels:
    app: streak-service
spec:
  type: ClusterIP
  selector:
    app: streak-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
