apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - ../../../base/ai-review-service

images:
  - name: ghcr.io/mihaicatalin22/questify-ai-review-service
    newTag: origin-ai-review-streak-service-3439eb6
