import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { toast } from "react-hot-toast";
import {
  ArrowUpRight,
  Bot,
  Clock3,
  RefreshCcw,
  Settings2,
  ShieldCheck,
  Sparkles,
  Target,
  TriangleAlert,
} from "lucide-react";

import type { CoachSuggestion, CoachSuggestionsResponse } from "../../api/coach";
import { useAuthContext } from "../../contexts/useAuthContext";
import { useCoachDashboardSummary, useCoachSettings, useGenerateCoachSuggestions } from "../../hooks/useCoach";
import {
  Badge,
  Button,
  EmptyState,
  ErrorState,
  LoadingState,
  PageHeader,
  PageShell,
  Panel,
} from "../../components/ui";
import { readIncludeRecentHistoryPreference } from "./coachPreferences";
import {
  getShownSuggestionTitles,
  getStoredAcceptedQuests,
  getStoredCoachResponse,
  mergeUniqueTitles,
  normalizeGoalKey,
  rememberShownSuggestionTitles,
  setStoredCoachResponse,
  suggestionKeyFor,
} from "./coachSession";

type GenerationViewState = "idle" | "loading" | "success" | "fallback" | "error";

type ApiErrorPayload = {
  message?: string;
  error?: string;
};

type HttpLikeError = {
  message?: string;
  response?: {
    data?: ApiErrorPayload;
  };
};

function formatDate(iso?: string | null) {
  if (!iso) return "Not yet";
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return String(iso);
  return date.toLocaleString();
}

function isHttpLikeError(error: unknown): error is HttpLikeError {
  return typeof error === "object" && error !== null;
}

function extractApiMessage(error: unknown, fallback: string) {
  if (!isHttpLikeError(error)) return fallback;

  const responseData = error?.response?.data;
  if (typeof responseData?.message === "string" && responseData.message.trim()) {
    return responseData.message;
  }
  if (typeof responseData?.error === "string" && responseData.error.trim()) {
    return responseData.error;
  }
  if (typeof error?.message === "string" && error.message.trim()) {
    return error.message;
  }
  return fallback;
}

function difficultyTone(difficulty: CoachSuggestion["difficulty"]): "success" | "warning" | "danger" {
  if (difficulty === "hard") return "danger";
  if (difficulty === "medium") return "warning";
  return "success";
}

function categoryLabel(category: string) {
  return category.replaceAll("_", " ");
}

function summaryValue(value: string | number | null | undefined) {
  if (value == null || value === "") return "—";
  return String(value);
}

export default function CoachPage() {
  const { user } = useAuthContext();
  const settingsQ = useCoachSettings();
  const summaryQ = useCoachDashboardSummary();
  const generateM = useGenerateCoachSuggestions();

  const [includeRecentHistory, setIncludeRecentHistory] = useState(true);
  const [suggestions, setSuggestions] = useState<CoachSuggestionsResponse | null>(() => getStoredCoachResponse());
  const [viewState, setViewState] = useState<GenerationViewState>(() => {
    const storedResponse = getStoredCoachResponse();
    if (!storedResponse) return "idle";
    return storedResponse.status === "FALLBACK" ? "fallback" : "success";
  });
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const acceptedQuests = getStoredAcceptedQuests();
  const hasAutoGeneratedRef = useRef(Boolean(getStoredCoachResponse()));

  useEffect(() => {
    setIncludeRecentHistory(readIncludeRecentHistoryPreference(user?.id));
  }, [user?.id]);

  useEffect(() => {
    if (!suggestions?.generatedAt) return;
    setStoredCoachResponse(suggestions);
  }, [suggestions]);

  useEffect(() => {
    if (!settingsQ.data?.aiCoachEnabled) {
      setSuggestions(null);
      setStoredCoachResponse(null);
      setViewState("idle");
      hasAutoGeneratedRef.current = false;
    }
  }, [settingsQ.data?.aiCoachEnabled]);

  const goalText = (settingsQ.data?.coachGoal ?? "").trim();
  const goalKey = useMemo(() => normalizeGoalKey(goalText), [goalText]);
  const canGenerate = Boolean(settingsQ.data?.aiCoachEnabled) && goalText.length > 0;

  const runGeneration = useCallback(
    async (nextIncludeRecentHistory = includeRecentHistory) => {
      if (!settingsQ.data?.aiCoachEnabled) {
        setSuggestions(null);
        setStoredCoachResponse(null);
        setErrorMessage(null);
        setViewState("idle");
        hasAutoGeneratedRef.current = false;
        return;
      }

      if (!goalText) {
        setErrorMessage("Set a coach goal before generating suggestions.");
        setViewState("error");
        return;
      }

      hasAutoGeneratedRef.current = true;
      setSuggestions(null);
      setStoredCoachResponse(null);
      setViewState("loading");
      setErrorMessage(null);

      try {
        const excludedSuggestionTitles = getShownSuggestionTitles(goalKey);

        const response = await generateM.mutateAsync({
          mode: "DEFAULT",
          includeRecentHistory: nextIncludeRecentHistory,
          excludedSuggestionTitles,
        });

        const returnedTitles = response.suggestions
          .map((suggestion) => suggestion.title.trim())
          .filter((title) => title.length > 0);
        rememberShownSuggestionTitles(goalKey, mergeUniqueTitles(excludedSuggestionTitles, returnedTitles));

        setSuggestions(response);
        setStoredCoachResponse(response);
        setViewState(response.status === "FALLBACK" ? "fallback" : "success");
      } catch (error: unknown) {
        const message = extractApiMessage(error, "Failed to generate coach suggestions");
        setSuggestions(null);
        setStoredCoachResponse(null);
        setErrorMessage(message);
        setViewState("error");
        toast.error(message);
      }
    },
    [generateM, goalKey, goalText, includeRecentHistory, settingsQ.data?.aiCoachEnabled]
  );

  useEffect(() => {
    if (!settingsQ.data?.aiCoachEnabled) return;
    if (!goalText) return;
    if (hasAutoGeneratedRef.current) return;

    hasAutoGeneratedRef.current = true;
    void runGeneration();
  }, [goalText, runGeneration, settingsQ.data?.aiCoachEnabled]);

  if (settingsQ.isLoading) return <LoadingState label="Loading AI Coach..." />;
  if (settingsQ.isError) {
    return <ErrorState message={extractApiMessage(settingsQ.error, "Failed to load coach settings")} />;
  }

  const displaySuggestions = suggestions?.suggestions ?? [];
  const isGenerating = generateM.isPending || viewState === "loading";
  const isSystemFallback = viewState === "fallback" && suggestions?.source === "SYSTEM";
  const statusLabel = !settingsQ.data?.aiCoachEnabled
    ? "Coach disabled"
    : isGenerating
      ? "Generating"
      : viewState === "fallback"
        ? "Fallback"
        : "Ready";

  const summaryItems = [
    {
      label: "Goal",
      value: goalText || "Set a saved goal in Coach Settings.",
      icon: Target,
      className: "md:col-span-2",
    },
    {
      label: "Active quests",
      value: summaryValue(summaryQ.data?.activeQuests),
      icon: Sparkles,
      className: "",
    },
    {
      label: "Completed quests",
      value: summaryValue(summaryQ.data?.completedQuests),
      icon: ShieldCheck,
      className: "",
    },
    {
      label: "Last refresh",
      value: suggestions?.generatedAt ? formatDate(suggestions.generatedAt) : "Not yet",
      icon: Clock3,
      className: "",
    },
  ] as const;

  return (
    <PageShell className="max-w-7xl">
      <PageHeader
        title="AI Coach"
        description="Generate realistic quest ideas from your saved goal, then inspect or review a suggestion before turning it into a quest."
        actions={
          <>
            <Button
              onClick={() => void runGeneration()}
              disabled={!canGenerate || isGenerating}
              variant="primary"
            >
              <Sparkles className="h-4 w-4" />
              {displaySuggestions.length > 0 ? "Generate fresh suggestions" : "Generate suggestions"}
            </Button>
            <Button
              onClick={() => void runGeneration()}
              disabled={!canGenerate || isGenerating}
            >
              <RefreshCcw className={`h-4 w-4 ${isGenerating ? "animate-spin" : ""}`} />
              Refresh coach
            </Button>
            <Link to="/coach/settings" className="btn btn-secondary">
              <Settings2 className="h-4 w-4" />
              Coach settings
            </Link>
          </>
        }
      />

      <Panel className="p-4">
        <div className="flex flex-wrap items-center gap-2">
          <Badge tone={statusLabel === "Ready" ? "success" : statusLabel === "Fallback" ? "warning" : "neutral"}>
            {statusLabel}
          </Badge>
          <Badge>History {includeRecentHistory ? "on" : "off"}</Badge>
          {suggestions?.generatedAt ? <Badge>Updated {formatDate(suggestions.generatedAt)}</Badge> : null}
        </div>
      </Panel>

      <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">
        {summaryItems.map((item) => {
          const Icon = item.icon;
          const valueClass =
            item.label === "Goal"
              ? "text-sm leading-6 text-[rgb(var(--text))]"
              : "text-xl font-semibold text-[rgb(var(--text))]";

          return (
            <Panel key={item.label} className={`p-4 ${item.className}`}>
              <div className="flex items-center gap-2 text-xs font-semibold text-[rgb(var(--muted))]">
                <Icon className="h-4 w-4" />
                {item.label}
              </div>
              <div className={`mt-3 ${valueClass}`}>{item.value}</div>
            </Panel>
          );
        })}
      </section>

      {!settingsQ.data?.aiCoachEnabled && (
        <EmptyState
          title="AI Coach is off for this account."
          description={
            <>
              Open <Link to="/coach/settings" className="link">Coach Settings</Link> to enable it and save a goal.
            </>
          }
        />
      )}

      {settingsQ.data?.aiCoachEnabled && !goalText && (
        <EmptyState
          title="Set a coach goal first."
          description={
            <>
              The coach needs a saved goal before it can generate useful suggestions. Open{" "}
              <Link to="/coach/settings" className="link">Coach Settings</Link> and add one.
            </>
          }
        />
      )}

      {canGenerate && viewState === "idle" && !suggestions && (
        <EmptyState
          title="No suggestions yet."
          description="Generate a coach pass to populate the quest feed for your saved goal."
        />
      )}

      {settingsQ.data?.aiCoachEnabled && viewState === "loading" && (
        <Panel className="p-6">
          <div className="flex items-start gap-3 text-sm text-[rgb(var(--muted))]">
            <RefreshCcw className="mt-0.5 h-4 w-4 animate-spin" />
            <div>
              <div>Generating personalized quest suggestions...</div>
              <div className="mt-1 text-xs text-[rgb(var(--faint))]">
                The local model still needs time for a full structured pass, especially after a cold start.
              </div>
            </div>
          </div>
        </Panel>
      )}

      {settingsQ.data?.aiCoachEnabled && viewState === "error" && (
        <div className="rounded-lg border border-[rgba(var(--coral),0.45)] bg-[rgba(var(--coral),0.1)] p-6 text-sm text-red-200">
          <div className="font-medium">Coach request failed</div>
          <div className="mt-1">{errorMessage ?? "Failed to generate coach suggestions."}</div>
        </div>
      )}

      {settingsQ.data?.aiCoachEnabled && suggestions && (viewState === "success" || viewState === "fallback") && (
        <>
          {isSystemFallback && (
            <div className="rounded-lg border border-[rgba(var(--amber),0.42)] bg-[rgba(var(--amber),0.1)] p-5 text-sm text-amber-100">
              <div className="flex items-start gap-3">
                <TriangleAlert className="mt-0.5 h-4 w-4 shrink-0" />
                <div>
                  <div className="font-semibold">AI suggestions were not available for this refresh.</div>
                  <div className="mt-1 text-sm leading-6 text-amber-100/85">
                    These are backup suggestions derived from your saved goal and recent coach context. You can still
                    accept them as quests, but they are less tailored than a successful AI pass.
                  </div>
                </div>
              </div>
            </div>
          )}

          {displaySuggestions.length > 0 ? (
            <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
              {displaySuggestions.map((suggestion, index) => {
                const suggestionKey = suggestionKeyFor(suggestions.generatedAt, suggestion, index);
                const acceptedQuest = acceptedQuests[suggestionKey];
                const detailsHref = `/coach/suggestions/${encodeURIComponent(suggestionKey)}`;
                const reviewHref = `${detailsHref}/review`;

                return (
                  <Panel
                    key={suggestionKey}
                    className="group flex h-full flex-col overflow-hidden transition hover:-translate-y-0.5 hover:border-[rgba(var(--accent),0.35)]"
                  >
                    <div className="flex h-full flex-col gap-4 p-5">
                      <div className="flex flex-wrap items-center gap-2 text-xs">
                        <Badge tone={difficultyTone(suggestion.difficulty)} className="capitalize">
                          {suggestion.difficulty}
                        </Badge>
                        <Badge>{suggestion.estimatedMinutes} min</Badge>
                        <Badge>{categoryLabel(suggestion.category)}</Badge>
                        {acceptedQuest ? <Badge tone="success">Accepted</Badge> : null}
                      </div>

                      <Link to={detailsHref} className="block min-w-0 rounded-lg focus:outline-none focus:ring-2 focus:ring-[rgba(var(--accent),0.7)]">
                        <h3 className="text-xl font-semibold text-[rgb(var(--text))]">
                          {suggestion.title}
                        </h3>
                        <p className="mt-2 text-sm leading-6 text-[rgb(var(--muted))]">
                          {suggestion.description}
                        </p>
                      </Link>

                      <Link
                        to={detailsHref}
                        className="block rounded-lg border border-[rgb(var(--border-soft))] bg-[rgba(var(--bg-soft),0.58)] px-4 py-3 text-sm leading-6 text-[rgb(var(--muted))] focus:outline-none focus:ring-2 focus:ring-[rgba(var(--accent),0.7)]"
                      >
                        {suggestion.reason}
                      </Link>

                      <div className="mt-auto flex flex-col gap-3 pt-2">
                        <div className="text-xs text-[rgb(var(--faint))]">
                          {acceptedQuest ? "Quest created from this card." : "Inspect the suggestion or go straight to review."}
                        </div>

                        <div className="flex justify-end">
                          {acceptedQuest ? (
                            <Link
                              to={`/quests/${acceptedQuest.questId}`}
                              className="btn btn-secondary"
                            >
                              View quest
                              <ArrowUpRight className="h-4 w-4" />
                            </Link>
                          ) : (
                            <Link
                              to={reviewHref}
                              className="btn btn-primary"
                            >
                              Accept as Quest
                            </Link>
                          )}
                        </div>
                      </div>
                    </div>
                  </Panel>
                );
              })}
            </div>
          ) : (
            <EmptyState
              title="The coach returned no quest cards."
              description="Try refreshing after adjusting your goal."
            />
          )}

          <div className="grid gap-4 lg:grid-cols-2">
            <Panel className="p-5">
              <div className="text-xs font-semibold text-[rgb(var(--muted))]">
                Reflection
              </div>
              <p className="mt-3 text-sm leading-6 text-[rgb(var(--muted))]">{suggestions.reflection}</p>
            </Panel>

            <Panel className="p-5">
              <div className="text-xs font-semibold text-[rgb(var(--muted))]">
                Nudge
              </div>
              <p className="mt-3 text-sm leading-6 text-[rgb(var(--muted))]">{suggestions.nudge}</p>
            </Panel>
          </div>
        </>
      )}

      <Panel className="p-5">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <h2 className="text-xl font-semibold text-[rgb(var(--text))]">Coach settings and quality</h2>
            <p className="mt-1 text-sm text-[rgb(var(--muted))]">
              Saved goal, AI opt-in, and history preference now live in a dedicated page instead of sitting under the feed.
            </p>
          </div>

          <Link to="/coach/settings" className="btn btn-secondary">
            <Bot className="h-4 w-4" />
            Open Coach Settings
          </Link>
        </div>
      </Panel>
    </PageShell>
  );
}
