import { useEffect, useEffectEvent, useRef, useState } from "react";
import { toast } from "react-hot-toast";
import { Bot, RefreshCcw, Sparkles } from "lucide-react";

import type { CoachSuggestionsResponse } from "../../api/coach";
import type { CoachSettingsDTO, UpdateCoachSettingsInput } from "../../api/users";
import {
  useCoachSettings,
  useGenerateCoachSuggestions,
  useUpdateCoachSettings,
} from "../../hooks/useCoach";

type GenerationViewState = "idle" | "loading" | "success" | "fallback" | "error";

type ApiErrorPayload = {
  message?: string;
  error?: string;
};

type HttpLikeError = {
  message?: string;
  response?: {
    data?: ApiErrorPayload;
  };
};

function formatDate(iso?: string | null) {
  if (!iso) return "—";
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return String(iso);
  return date.toLocaleString();
}

function isHttpLikeError(error: unknown): error is HttpLikeError {
  return typeof error === "object" && error !== null;
}

function extractApiMessage(error: unknown, fallback: string) {
  if (!isHttpLikeError(error)) return fallback;

  const responseData = error?.response?.data;
  if (typeof responseData?.message === "string" && responseData.message.trim()) {
    return responseData.message;
  }
  if (typeof responseData?.error === "string" && responseData.error.trim()) {
    return responseData.error;
  }
  if (typeof error?.message === "string" && error.message.trim()) {
    return error.message;
  }
  return fallback;
}

function mapSettingsToForm(settings?: CoachSettingsDTO | null): UpdateCoachSettingsInput {
  return {
    aiCoachEnabled: Boolean(settings?.aiCoachEnabled),
    coachGoal: settings?.coachGoal ?? "",
  };
}

export default function CoachPage() {
  const settingsQ = useCoachSettings();
  const saveSettingsM = useUpdateCoachSettings();
  const generateM = useGenerateCoachSuggestions();

  const [settingsForm, setSettingsForm] = useState<UpdateCoachSettingsInput>({
    aiCoachEnabled: false,
    coachGoal: "",
  });
  const [includeRecentHistory, setIncludeRecentHistory] = useState(true);
  const [suggestions, setSuggestions] = useState<CoachSuggestionsResponse | null>(null);
  const [viewState, setViewState] = useState<GenerationViewState>("idle");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const hasAutoGeneratedRef = useRef(false);

  useEffect(() => {
    if (!settingsQ.data) return;
    setSettingsForm(mapSettingsToForm(settingsQ.data));
  }, [settingsQ.data]);

  const runGeneration = useEffectEvent(async (nextIncludeRecentHistory = includeRecentHistory) => {
    setViewState("loading");
    setErrorMessage(null);

    try {
      const response = await generateM.mutateAsync({
        mode: "DEFAULT",
        includeRecentHistory: nextIncludeRecentHistory,
      });

      setSuggestions(response);
      setViewState(response.status === "FALLBACK" ? "fallback" : "success");
    } catch (error: unknown) {
      const message = extractApiMessage(error, "Failed to generate coach suggestions");
      setSuggestions(null);
      setErrorMessage(message);
      setViewState("error");
      toast.error(message);
    }
  });

  async function onSaveSettings() {
    try {
      const saved = await saveSettingsM.mutateAsync({
        aiCoachEnabled: Boolean(settingsForm.aiCoachEnabled),
        coachGoal: settingsForm.coachGoal ?? "",
      });

      setSettingsForm(mapSettingsToForm(saved));
      toast.success("Coach settings saved");

      if (!saved.aiCoachEnabled) {
        setSuggestions(null);
        setErrorMessage(null);
        setViewState("idle");
        hasAutoGeneratedRef.current = false;
        return;
      }

      hasAutoGeneratedRef.current = true;
      await runGeneration();
    } catch (error: unknown) {
      toast.error(extractApiMessage(error, "Failed to save coach settings"));
    }
  }

  useEffect(() => {
    if (!settingsQ.data) return;
    if (!settingsQ.data.aiCoachEnabled) return;
    if (hasAutoGeneratedRef.current) return;

    hasAutoGeneratedRef.current = true;
    void runGeneration();
  }, [runGeneration, settingsQ.data]);

  const persistedOptIn = Boolean(settingsQ.data?.aiCoachEnabled);
  const draftOptIn = Boolean(settingsForm.aiCoachEnabled);
  const isGenerating = generateM.isPending || viewState === "loading";
  const generationDisabled = !draftOptIn || saveSettingsM.isPending || isGenerating || settingsQ.isLoading;

  if (settingsQ.isLoading) {
    return <div className="p-6 opacity-70">Loading AI Coach…</div>;
  }

  if (settingsQ.isError) {
    return (
      <div className="p-6 text-red-600">
        {extractApiMessage(settingsQ.error, "Failed to load coach settings")}
      </div>
    );
  }

  return (
    <div className="max-w-6xl space-y-6 p-6">
      <div className="flex flex-col gap-2">
        <div className="inline-flex w-fit items-center gap-2 rounded-full border border-slate-200 bg-white px-3 py-1 text-xs font-medium text-slate-600 dark:border-slate-800 dark:bg-[#0f1115] dark:text-slate-300">
          <Sparkles className="h-3.5 w-3.5" />
          AI Coach
        </div>
        <div>
          <h1 className="text-2xl font-semibold text-slate-900 dark:text-slate-100">Questify Coach</h1>
          <p className="mt-1 text-sm text-slate-600 dark:text-slate-300">
            Personalized suggestions based on your goal, recent quest titles, and compact progress signals.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-6 xl:grid-cols-[minmax(320px,1fr)_minmax(0,1.4fr)]">
        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-[#0f1115]">
          <div className="flex items-center gap-2">
            <Bot className="h-5 w-5 text-slate-500 dark:text-slate-300" />
            <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">Coach Settings</h2>
          </div>

          <p className="mt-2 text-sm text-slate-600 dark:text-slate-300">
            Suggestions use only minimal recent quest context. Proof uploads, media, and unrelated profile data are
            not included.
          </p>

          <div className="mt-5 space-y-5">
            <label className="flex items-start gap-3 rounded-2xl border border-slate-200 p-4 dark:border-slate-800">
              <input
                type="checkbox"
                checked={draftOptIn}
                onChange={(event) =>
                  setSettingsForm((current) => ({
                    ...current,
                    aiCoachEnabled: event.target.checked,
                  }))
                }
                className="mt-1 h-4 w-4 rounded border-slate-300 text-slate-900 focus:ring-slate-400"
              />
              <div>
                <div className="text-sm font-medium text-slate-900 dark:text-slate-100">Enable AI Coach</div>
                <div className="text-xs text-slate-600 dark:text-slate-300">
                  Required before the coach can generate suggestions for your account.
                </div>
              </div>
            </label>

            <div>
              <label className="block text-xs opacity-70">Goal</label>
              <textarea
                value={settingsForm.coachGoal ?? ""}
                onChange={(event) =>
                  setSettingsForm((current) => ({
                    ...current,
                    coachGoal: event.target.value,
                  }))
                }
                rows={5}
                placeholder="Example: Stay consistent with short evening walks and easy recovery habits."
                className="mt-1 w-full rounded-2xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-800 dark:bg-[#0b0d12]"
              />
            </div>

            <label className="flex items-start gap-3 rounded-2xl border border-slate-200 p-4 dark:border-slate-800">
              <input
                type="checkbox"
                checked={includeRecentHistory}
                onChange={(event) => setIncludeRecentHistory(event.target.checked)}
                className="mt-1 h-4 w-4 rounded border-slate-300 text-slate-900 focus:ring-slate-400"
              />
              <div>
                <div className="text-sm font-medium text-slate-900 dark:text-slate-100">Include recent history</div>
                <div className="text-xs text-slate-600 dark:text-slate-300">
                  Let the coach use recent completion timestamps and quest titles for tighter suggestions.
                </div>
              </div>
            </label>

            <div className="flex flex-wrap items-center gap-2">
              <button
                onClick={onSaveSettings}
                disabled={saveSettingsM.isPending}
                className="rounded-2xl border border-slate-200 bg-white px-4 py-2 text-sm shadow hover:shadow-md disabled:opacity-60 dark:border-slate-800 dark:bg-[#0f1115]"
              >
                {saveSettingsM.isPending ? "Saving…" : "Save coach settings"}
              </button>

              {!persistedOptIn && (
                <span className="text-xs text-amber-700 dark:text-amber-300">
                  Enable AI Coach and save before generating suggestions.
                </span>
              )}
            </div>
          </div>
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-[#0f1115]">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">Suggestions</h2>
              <p className="mt-1 text-sm text-slate-600 dark:text-slate-300">
                The coach auto-loads once per visit when opt-in is enabled. You can refresh anytime.
              </p>
            </div>

            <button
              onClick={() => void runGeneration()}
              disabled={generationDisabled}
              className="inline-flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 py-2 text-sm shadow hover:shadow-md disabled:opacity-60 dark:border-slate-800 dark:bg-[#0f1115]"
            >
              <RefreshCcw className={`h-4 w-4 ${isGenerating ? "animate-spin" : ""}`} />
              {isGenerating ? "Generating…" : "Refresh suggestions"}
            </button>
          </div>

          <div className="mt-5 space-y-4">
            {!draftOptIn && (
              <div className="rounded-2xl border border-dashed border-slate-300 p-5 text-sm text-slate-600 dark:border-slate-700 dark:text-slate-300">
                AI Coach is currently off. Enable it in the settings panel and save to generate suggestions.
              </div>
            )}

            {draftOptIn && viewState === "idle" && (
              <div className="rounded-2xl border border-dashed border-slate-300 p-5 text-sm text-slate-600 dark:border-slate-700 dark:text-slate-300">
                No suggestions yet. Save your coach settings or refresh to generate a new set.
              </div>
            )}

            {draftOptIn && viewState === "loading" && (
              <div className="rounded-2xl border border-slate-200 p-5 text-sm text-slate-600 dark:border-slate-800 dark:text-slate-300">
                Generating personalized suggestions…
              </div>
            )}

            {draftOptIn && viewState === "error" && (
              <div className="rounded-2xl border border-red-200 p-5 text-sm text-red-700 dark:border-red-900 dark:text-red-300">
                <div className="font-medium">Coach request failed</div>
                <div className="mt-1">{errorMessage ?? "Failed to generate coach suggestions."}</div>
              </div>
            )}

            {draftOptIn && suggestions && (viewState === "success" || viewState === "fallback") && (
              <>
                <div className="flex flex-wrap items-center gap-2 text-xs">
                  <span className="rounded-full border border-slate-200 px-2 py-1 dark:border-slate-800">
                    Status: {suggestions.status}
                  </span>
                  <span className="rounded-full border border-slate-200 px-2 py-1 dark:border-slate-800">
                    Source: {suggestions.source}
                  </span>
                  {suggestions.model && (
                    <span className="rounded-full border border-slate-200 px-2 py-1 dark:border-slate-800">
                      Model: {suggestions.model}
                    </span>
                  )}
                  <span className="rounded-full border border-slate-200 px-2 py-1 dark:border-slate-800">
                    Generated: {formatDate(suggestions.generatedAt)}
                  </span>
                </div>

                {suggestions.suggestions.length > 0 ? (
                  <div className="grid grid-cols-1 gap-4 lg:grid-cols-3">
                    {suggestions.suggestions.map((suggestion, index) => (
                      <article
                        key={`${suggestion.title}-${index}`}
                        className="rounded-2xl border border-slate-200 p-4 dark:border-slate-800"
                      >
                        <div className="flex items-start justify-between gap-3">
                          <h3 className="text-sm font-semibold text-slate-900 dark:text-slate-100">
                            {suggestion.title}
                          </h3>
                          <span className="rounded-full border border-slate-200 px-2 py-1 text-[11px] capitalize dark:border-slate-800">
                            {suggestion.difficulty}
                          </span>
                        </div>

                        <div className="mt-2 text-xs text-slate-500 dark:text-slate-400">
                          {suggestion.estimatedMinutes} minute{suggestion.estimatedMinutes === 1 ? "" : "s"}
                        </div>

                        <p className="mt-3 text-sm text-slate-600 dark:text-slate-300">{suggestion.reason}</p>
                      </article>
                    ))}
                  </div>
                ) : (
                  <div className="rounded-2xl border border-slate-200 p-5 text-sm text-slate-600 dark:border-slate-800 dark:text-slate-300">
                    The coach returned a safe fallback without suggestion cards. You can try again at any time.
                  </div>
                )}

                <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
                  <div className="rounded-2xl border border-slate-200 p-4 dark:border-slate-800">
                    <div className="text-xs font-medium uppercase tracking-wide text-slate-500 dark:text-slate-400">
                      Reflection
                    </div>
                    <p className="mt-2 text-sm text-slate-700 dark:text-slate-200">{suggestions.reflection}</p>
                  </div>

                  <div className="rounded-2xl border border-slate-200 p-4 dark:border-slate-800">
                    <div className="text-xs font-medium uppercase tracking-wide text-slate-500 dark:text-slate-400">
                      Nudge
                    </div>
                    <p className="mt-2 text-sm text-slate-700 dark:text-slate-200">{suggestions.nudge}</p>
                  </div>
                </div>
              </>
            )}
          </div>
        </section>
      </div>
    </div>
  );
}
