import { useEffect, useEffectEvent, useMemo, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { toast } from "react-hot-toast";
import {
  ArrowUpRight,
  Bot,
  ChevronDown,
  ChevronUp,
  Clock3,
  RefreshCcw,
  ShieldCheck,
  Sparkles,
  Target,
} from "lucide-react";

import type { CoachSuggestion, CoachSuggestionsResponse } from "../../api/coach";
import type { CoachSettingsDTO, UpdateCoachSettingsInput } from "../../api/users";
import type { QuestCategory } from "../../types/quest";
import { useAuthContext } from "../../contexts/AuthContext";
import { useCreateQuest } from "../../hooks/useQuests";
import {
  useCoachDashboardSummary,
  useCoachSettings,
  useGenerateCoachSuggestions,
  useUpdateCoachSettings,
} from "../../hooks/useCoach";

type GenerationViewState = "idle" | "loading" | "success" | "fallback" | "error";

type ApiErrorPayload = {
  message?: string;
  error?: string;
};

type HttpLikeError = {
  message?: string;
  response?: {
    data?: ApiErrorPayload;
  };
};

type AcceptedQuestState = {
  questId: number;
  title: string;
};

type ReviewDraft = {
  suggestionKey: string;
  title: string;
  description: string;
  category: QuestCategory;
  difficulty: CoachSuggestion["difficulty"];
  estimatedMinutes: number;
  reason: string;
};

const QUEST_CATEGORIES: QuestCategory[] = [
  "COMMUNITY",
  "FITNESS",
  "HABIT",
  "HOBBY",
  "OTHER",
  "STUDY",
  "WORK",
];

function formatDate(iso?: string | null) {
  if (!iso) return "Not yet";
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return String(iso);
  return date.toLocaleString();
}

function plusSevenDaysIso(startIso: string) {
  const start = new Date(startIso);
  return new Date(start.getTime() + 7 * 24 * 60 * 60 * 1000).toISOString();
}

function isHttpLikeError(error: unknown): error is HttpLikeError {
  return typeof error === "object" && error !== null;
}

function extractApiMessage(error: unknown, fallback: string) {
  if (!isHttpLikeError(error)) return fallback;

  const responseData = error?.response?.data;
  if (typeof responseData?.message === "string" && responseData.message.trim()) {
    return responseData.message;
  }
  if (typeof responseData?.error === "string" && responseData.error.trim()) {
    return responseData.error;
  }
  if (typeof error?.message === "string" && error.message.trim()) {
    return error.message;
  }
  return fallback;
}

function mapSettingsToForm(settings?: CoachSettingsDTO | null): UpdateCoachSettingsInput {
  return {
    aiCoachEnabled: Boolean(settings?.aiCoachEnabled),
    coachGoal: settings?.coachGoal ?? "",
  };
}

function suggestionKeyFor(generatedAt: string, suggestion: CoachSuggestion, index: number) {
  return `${generatedAt}:${index}:${suggestion.title}`;
}

function summaryValue(value: string | number | null | undefined) {
  if (value == null || value === "") return "—";
  return String(value);
}

function difficultyTone(difficulty: CoachSuggestion["difficulty"]) {
  if (difficulty === "hard") {
    return "border-rose-200 bg-rose-50 text-rose-700 dark:border-rose-900/60 dark:bg-rose-950/40 dark:text-rose-200";
  }
  if (difficulty === "medium") {
    return "border-amber-200 bg-amber-50 text-amber-700 dark:border-amber-900/60 dark:bg-amber-950/40 dark:text-amber-200";
  }
  return "border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900/60 dark:bg-emerald-950/40 dark:text-emerald-200";
}

function categoryLabel(category: QuestCategory) {
  return category.replaceAll("_", " ");
}

export default function CoachPage() {
  const { user } = useAuthContext();
  const settingsQ = useCoachSettings();
  const summaryQ = useCoachDashboardSummary();
  const saveSettingsM = useUpdateCoachSettings();
  const generateM = useGenerateCoachSuggestions();
  const createQuestM = useCreateQuest();

  const [settingsForm, setSettingsForm] = useState<UpdateCoachSettingsInput>({
    aiCoachEnabled: false,
    coachGoal: "",
  });
  const [includeRecentHistory, setIncludeRecentHistory] = useState(true);
  const [suggestions, setSuggestions] = useState<CoachSuggestionsResponse | null>(null);
  const [viewState, setViewState] = useState<GenerationViewState>("idle");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [settingsExpanded, setSettingsExpanded] = useState(false);
  const [reviewDraft, setReviewDraft] = useState<ReviewDraft | null>(null);
  const [acceptedQuests, setAcceptedQuests] = useState<Record<string, AcceptedQuestState>>({});

  const hasAutoGeneratedRef = useRef(false);
  const settingsRef = useRef<HTMLElement | null>(null);

  useEffect(() => {
    if (!settingsQ.data) return;
    setSettingsForm(mapSettingsToForm(settingsQ.data));
  }, [settingsQ.data]);

  useEffect(() => {
    setAcceptedQuests({});
  }, [suggestions?.generatedAt]);

  const runGeneration = useEffectEvent(async (nextIncludeRecentHistory = includeRecentHistory) => {
    setViewState("loading");
    setErrorMessage(null);

    try {
      const response = await generateM.mutateAsync({
        mode: "DEFAULT",
        includeRecentHistory: nextIncludeRecentHistory,
      });

      setSuggestions(response);
      setViewState(response.status === "FALLBACK" ? "fallback" : "success");
    } catch (error: unknown) {
      const message = extractApiMessage(error, "Failed to generate coach suggestions");
      setSuggestions(null);
      setErrorMessage(message);
      setViewState("error");
      toast.error(message);
    }
  });

  async function onSaveSettings() {
    try {
      const saved = await saveSettingsM.mutateAsync({
        aiCoachEnabled: Boolean(settingsForm.aiCoachEnabled),
        coachGoal: settingsForm.coachGoal ?? "",
      });

      setSettingsForm(mapSettingsToForm(saved));
      toast.success("Coach settings saved");

      if (!saved.aiCoachEnabled) {
        setSuggestions(null);
        setErrorMessage(null);
        setViewState("idle");
        hasAutoGeneratedRef.current = false;
        return;
      }

      hasAutoGeneratedRef.current = true;
      await runGeneration();
    } catch (error: unknown) {
      toast.error(extractApiMessage(error, "Failed to save coach settings"));
    }
  }

  useEffect(() => {
    if (!settingsQ.data) return;
    if (!settingsQ.data.aiCoachEnabled) return;
    if (hasAutoGeneratedRef.current) return;

    hasAutoGeneratedRef.current = true;
    void runGeneration();
  }, [runGeneration, settingsQ.data]);

  function revealSettings() {
    setSettingsExpanded(true);
    settingsRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
  }

  function openReviewForSuggestion(suggestion: CoachSuggestion, index: number) {
    if (!suggestions?.generatedAt) return;
    const key = suggestionKeyFor(suggestions.generatedAt, suggestion, index);
    if (acceptedQuests[key]) return;

    setReviewDraft({
      suggestionKey: key,
      title: suggestion.title,
      description: suggestion.description,
      category: suggestion.category,
      difficulty: suggestion.difficulty,
      estimatedMinutes: suggestion.estimatedMinutes,
      reason: suggestion.reason,
    });
  }

  async function confirmQuestCreation() {
    if (!reviewDraft) return;
    if (!user?.id) {
      toast.error("You need to be logged in to create a quest.");
      return;
    }

    const title = reviewDraft.title.trim();
    const description = reviewDraft.description.trim();

    if (title.length < 3) {
      toast.error("Quest title must be at least 3 characters.");
      return;
    }
    if (description.length < 10) {
      toast.error("Quest description must be at least 10 characters.");
      return;
    }

    const startDate = new Date().toISOString();
    const endDate = plusSevenDaysIso(startDate);

    try {
      const createdQuest = await createQuestM.mutateAsync({
        title,
        description,
        category: reviewDraft.category,
        startDate,
        endDate,
        createdByUserId: String(user.id),
        visibility: "PRIVATE",
      });

      setAcceptedQuests((current) => ({
        ...current,
        [reviewDraft.suggestionKey]: {
          questId: createdQuest.id,
          title: createdQuest.title,
        },
      }));
      setReviewDraft(null);
      await summaryQ.refetch();
      toast.success("Quest created from coach suggestion");
    } catch (error: unknown) {
      toast.error(extractApiMessage(error, "Failed to create quest from suggestion"));
    }
  }

  const persistedOptIn = Boolean(settingsQ.data?.aiCoachEnabled);
  const draftOptIn = Boolean(settingsForm.aiCoachEnabled);
  const isGenerating = generateM.isPending || viewState === "loading";
  const generationDisabled =
    !draftOptIn || !persistedOptIn || saveSettingsM.isPending || isGenerating || settingsQ.isLoading;
  const quickActionsDisabled = settingsQ.isLoading || saveSettingsM.isPending || isGenerating;

  const heroGoal = useMemo(() => {
    const goal = (settingsForm.coachGoal ?? "").trim();
    return goal || "Add a goal to help the coach aim the next quest suggestions.";
  }, [settingsForm.coachGoal]);

  const summaryItems = [
    {
      label: "Goal",
      value: heroGoal,
      icon: Target,
      accent: "from-cyan-500/20 to-transparent",
    },
    {
      label: "Active quests",
      value: summaryValue(summaryQ.data?.activeQuests),
      icon: Sparkles,
      accent: "from-emerald-500/20 to-transparent",
    },
    {
      label: "Completed quests",
      value: summaryValue(summaryQ.data?.completedQuests),
      icon: ShieldCheck,
      accent: "from-amber-500/20 to-transparent",
    },
    {
      label: "Last coach refresh",
      value: suggestions?.generatedAt ? formatDate(suggestions.generatedAt) : "Not yet",
      icon: Clock3,
      accent: "from-fuchsia-500/20 to-transparent",
    },
  ] as const;

  if (settingsQ.isLoading) {
    return <div className="p-6 opacity-70">Loading AI Coach…</div>;
  }

  if (settingsQ.isError) {
    return (
      <div className="p-6 text-red-600">
        {extractApiMessage(settingsQ.error, "Failed to load coach settings")}
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-7xl space-y-6 px-2 pb-10 sm:px-4">
      {reviewDraft && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4">
          <div className="w-full max-w-2xl overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-2xl dark:border-slate-800 dark:bg-[#11161f]">
            <div className="border-b border-slate-200 bg-slate-50/80 px-6 py-4 dark:border-slate-800 dark:bg-[#161d29]">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <div className="text-xs font-semibold uppercase tracking-[0.24em] text-slate-500 dark:text-slate-400">
                    Review Quest
                  </div>
                  <h2 className="mt-1 text-xl font-semibold text-slate-950 dark:text-slate-50">
                    Create this coach suggestion as a quest
                  </h2>
                  <p className="mt-1 text-sm text-slate-600 dark:text-slate-300">
                    You can refine the AI-generated quest before it is saved. It will start immediately and end in 7
                    days.
                  </p>
                </div>
                <button
                  onClick={() => setReviewDraft(null)}
                  className="rounded-full border border-slate-200 px-3 py-1 text-sm text-slate-600 hover:bg-slate-100 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800"
                >
                  Close
                </button>
              </div>
            </div>

            <div className="space-y-5 px-6 py-5">
              <div className="grid gap-4 md:grid-cols-[minmax(0,1.3fr)_minmax(220px,0.7fr)]">
                <div className="space-y-4">
                  <div>
                    <label className="block text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
                      Title
                    </label>
                    <input
                      value={reviewDraft.title}
                      onChange={(event) =>
                        setReviewDraft((current) =>
                          current
                            ? {
                                ...current,
                                title: event.target.value,
                              }
                            : current
                        )
                      }
                      className="mt-1 w-full rounded-2xl border border-slate-200 bg-white px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-[#0d131c]"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
                      Description
                    </label>
                    <textarea
                      rows={5}
                      value={reviewDraft.description}
                      onChange={(event) =>
                        setReviewDraft((current) =>
                          current
                            ? {
                                ...current,
                                description: event.target.value,
                              }
                            : current
                        )
                      }
                      className="mt-1 w-full rounded-2xl border border-slate-200 bg-white px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-[#0d131c]"
                    />
                  </div>
                </div>

                <div className="space-y-4">
                  <div>
                    <label className="block text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
                      Category
                    </label>
                    <select
                      value={reviewDraft.category}
                      onChange={(event) =>
                        setReviewDraft((current) =>
                          current
                            ? {
                                ...current,
                                category: event.target.value as QuestCategory,
                              }
                            : current
                        )
                      }
                      className="mt-1 w-full rounded-2xl border border-slate-200 bg-white px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-[#0d131c]"
                    >
                      {QUEST_CATEGORIES.map((category) => (
                        <option key={category} value={category}>
                          {categoryLabel(category)}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-[#161d29]">
                    <div className="text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
                      Coach Signals
                    </div>
                    <div className="mt-3 flex flex-wrap gap-2">
                      <span
                        className={`rounded-full border px-2.5 py-1 text-xs font-medium capitalize ${difficultyTone(
                          reviewDraft.difficulty
                        )}`}
                      >
                        {reviewDraft.difficulty}
                      </span>
                      <span className="rounded-full border border-slate-200 px-2.5 py-1 text-xs font-medium text-slate-700 dark:border-slate-700 dark:text-slate-200">
                        {reviewDraft.estimatedMinutes} min
                      </span>
                      <span className="rounded-full border border-slate-200 px-2.5 py-1 text-xs font-medium text-slate-700 dark:border-slate-700 dark:text-slate-200">
                        Private quest
                      </span>
                    </div>

                    <div className="mt-4 space-y-2 text-sm text-slate-600 dark:text-slate-300">
                      <div>Starts immediately when you confirm.</div>
                      <div>Ends exactly 7 days later.</div>
                    </div>
                  </div>

                  <div className="rounded-2xl border border-slate-200 p-4 text-sm text-slate-600 dark:border-slate-800 dark:text-slate-300">
                    <div className="text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
                      Why the coach suggested it
                    </div>
                    <p className="mt-2">{reviewDraft.reason}</p>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex flex-wrap items-center justify-end gap-3 border-t border-slate-200 px-6 py-4 dark:border-slate-800">
              <button
                onClick={() => setReviewDraft(null)}
                className="rounded-2xl border border-slate-200 px-4 py-2 text-sm text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-200 dark:hover:bg-slate-800"
              >
                Cancel
              </button>
              <button
                onClick={confirmQuestCreation}
                disabled={createQuestM.isPending}
                className="rounded-2xl bg-slate-950 px-4 py-2 text-sm font-medium text-white shadow-lg shadow-slate-950/20 hover:bg-slate-800 disabled:opacity-60 dark:bg-slate-100 dark:text-slate-950 dark:hover:bg-white"
              >
                {createQuestM.isPending ? "Creating quest…" : "Create quest"}
              </button>
            </div>
          </div>
        </div>
      )}

      <section className="relative overflow-hidden rounded-[32px] border border-slate-200 bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 p-6 text-white shadow-[0_20px_60px_-20px_rgba(15,23,42,0.55)] dark:border-slate-800">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(45,212,191,0.18),transparent_35%),radial-gradient(circle_at_bottom_right,rgba(251,191,36,0.16),transparent_28%)]" />
        <div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
          <div className="max-w-3xl">
            <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs font-medium text-white/80 backdrop-blur">
              <Sparkles className="h-3.5 w-3.5 text-cyan-300" />
              AI Coach
            </div>
            <h1 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Coach</h1>
            <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300 sm:text-base">
              Your AI quest coach helps you decide what to do next, then turn the best suggestion into a quest without
              leaving this page.
            </p>
          </div>

          <div className="grid gap-3 sm:grid-cols-2">
            <div className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3 backdrop-blur">
              <div className="text-[11px] font-semibold uppercase tracking-[0.22em] text-slate-400">Status</div>
              <div className="mt-2 text-sm font-medium text-slate-50">
                {draftOptIn ? (isGenerating ? "Generating" : "Ready") : "Coach disabled"}
              </div>
            </div>
            <div className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3 backdrop-blur">
              <div className="text-[11px] font-semibold uppercase tracking-[0.22em] text-slate-400">Model</div>
              <div className="mt-2 text-sm font-medium text-slate-50">{suggestions?.model ?? "smollm2:1.7b"}</div>
            </div>
          </div>
        </div>
      </section>

      <div className="grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_360px]">
        <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-[#131a25]">
          <div className="flex items-center justify-between gap-4">
            <div>
              <h2 className="text-2xl font-semibold text-slate-950 dark:text-slate-50">Today&apos;s Summary</h2>
              <p className="mt-1 text-sm text-slate-600 dark:text-slate-300">
                A quick snapshot of what the coach knows about your current direction.
              </p>
            </div>
            {summaryQ.isFetching && (
              <span className="rounded-full border border-slate-200 px-2.5 py-1 text-xs text-slate-500 dark:border-slate-700 dark:text-slate-400">
                Refreshing…
              </span>
            )}
          </div>

          <div className="mt-6 grid gap-4 md:grid-cols-2">
            {summaryItems.map((item) => {
              const Icon = item.icon;
              const valueClass =
                item.label === "Goal"
                  ? "text-sm leading-6 text-slate-900 dark:text-slate-50"
                  : "text-2xl font-semibold text-slate-950 dark:text-slate-50";

              return (
                <article
                  key={item.label}
                  className="relative overflow-hidden rounded-[24px] border border-slate-200 bg-slate-50/80 p-4 dark:border-slate-800 dark:bg-[#0d131c]"
                >
                  <div className={`pointer-events-none absolute inset-0 bg-gradient-to-br ${item.accent}`} />
                  <div className="relative">
                    <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.22em] text-slate-500 dark:text-slate-400">
                      <Icon className="h-4 w-4" />
                      {item.label}
                    </div>
                    <div className={`mt-3 ${valueClass}`}>{item.value}</div>
                  </div>
                </article>
              );
            })}
          </div>
        </section>

        <aside className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-[#131a25]">
          <h2 className="text-2xl font-semibold text-slate-950 dark:text-slate-50">Quick Actions</h2>
          <p className="mt-1 text-sm text-slate-600 dark:text-slate-300">
            Generate a fresh coach pass, refresh the current one, or jump to settings.
          </p>

          <div className="mt-6 space-y-3">
            <button
              onClick={() => void runGeneration()}
              disabled={quickActionsDisabled || !draftOptIn || !persistedOptIn}
              className="flex w-full items-center justify-between rounded-[20px] border border-slate-200 bg-slate-50 px-4 py-4 text-left transition hover:border-slate-300 hover:bg-white disabled:cursor-not-allowed disabled:opacity-60 dark:border-slate-800 dark:bg-[#0d131c] dark:hover:border-slate-700 dark:hover:bg-[#121925]"
            >
              <div>
                <div className="text-sm font-semibold text-slate-950 dark:text-slate-50">Generate Suggestions</div>
                <div className="mt-1 text-xs text-slate-500 dark:text-slate-400">
                  Run the coach with your saved goal and current history settings.
                </div>
              </div>
              <Sparkles className="h-4 w-4 text-cyan-500" />
            </button>

            <button
              onClick={() => void runGeneration()}
              disabled={generationDisabled}
              className="flex w-full items-center justify-between rounded-[20px] border border-slate-200 bg-slate-50 px-4 py-4 text-left transition hover:border-slate-300 hover:bg-white disabled:cursor-not-allowed disabled:opacity-60 dark:border-slate-800 dark:bg-[#0d131c] dark:hover:border-slate-700 dark:hover:bg-[#121925]"
            >
              <div>
                <div className="text-sm font-semibold text-slate-950 dark:text-slate-50">Refresh Coach</div>
                <div className="mt-1 text-xs text-slate-500 dark:text-slate-400">
                  {isGenerating ? "Generation is already running." : "Request a fresh set of suggestion cards."}
                </div>
              </div>
              <RefreshCcw className={`h-4 w-4 text-slate-500 ${isGenerating ? "animate-spin" : ""}`} />
            </button>

            <button
              onClick={revealSettings}
              className="flex w-full items-center justify-between rounded-[20px] border border-slate-200 bg-slate-50 px-4 py-4 text-left transition hover:border-slate-300 hover:bg-white dark:border-slate-800 dark:bg-[#0d131c] dark:hover:border-slate-700 dark:hover:bg-[#121925]"
            >
              <div>
                <div className="text-sm font-semibold text-slate-950 dark:text-slate-50">Open Settings</div>
                <div className="mt-1 text-xs text-slate-500 dark:text-slate-400">
                  Expand the AI/privacy panel and adjust goal or history usage.
                </div>
              </div>
              <Bot className="h-4 w-4 text-slate-500" />
            </button>
          </div>
        </aside>
      </div>

      <section className="space-y-4">
        <div className="flex items-end justify-between gap-4">
          <div>
            <h2 className="text-2xl font-semibold text-slate-950 dark:text-slate-50">Suggested Next Quests</h2>
            <p className="mt-1 text-sm text-slate-600 dark:text-slate-300">
              Review the coach suggestions, then accept one directly as a private quest.
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-2 text-xs">
            {suggestions && (
              <>
                <span className="rounded-full border border-slate-200 px-2.5 py-1 dark:border-slate-800">
                  Status: {suggestions.status}
                </span>
                <span className="rounded-full border border-slate-200 px-2.5 py-1 dark:border-slate-800">
                  Source: {suggestions.source}
                </span>
                {suggestions.model && (
                  <span className="rounded-full border border-slate-200 px-2.5 py-1 dark:border-slate-800">
                    Model: {suggestions.model}
                  </span>
                )}
              </>
            )}
          </div>
        </div>

        {(!draftOptIn || !persistedOptIn) && (
          <div className="rounded-[24px] border border-dashed border-slate-300 bg-white p-6 text-sm text-slate-600 dark:border-slate-700 dark:bg-[#131a25] dark:text-slate-300">
            {draftOptIn && !persistedOptIn
              ? "AI Coach is enabled in the draft settings, but not saved yet. Save your settings before generating quest suggestions."
              : "AI Coach is currently off. Open the settings panel below, enable it, and save before generating quest suggestions."}
          </div>
        )}

        {draftOptIn && persistedOptIn && viewState === "idle" && (
          <div className="rounded-[24px] border border-dashed border-slate-300 bg-white p-6 text-sm text-slate-600 dark:border-slate-700 dark:bg-[#131a25] dark:text-slate-300">
            No suggestions yet. Generate a coach pass to populate the quest feed.
          </div>
        )}

        {draftOptIn && viewState === "loading" && (
          <div className="rounded-[24px] border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-[#131a25]">
            <div className="flex items-center gap-3 text-sm text-slate-600 dark:text-slate-300">
              <RefreshCcw className="h-4 w-4 animate-spin" />
              Generating personalized quest suggestions…
            </div>
          </div>
        )}

        {draftOptIn && viewState === "error" && (
          <div className="rounded-[24px] border border-red-200 bg-red-50/80 p-6 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/30 dark:text-red-300">
            <div className="font-medium">Coach request failed</div>
            <div className="mt-1">{errorMessage ?? "Failed to generate coach suggestions."}</div>
          </div>
        )}

        {draftOptIn && suggestions && (viewState === "success" || viewState === "fallback") && (
          <>
            {suggestions.suggestions.length > 0 ? (
              <div className="space-y-4">
                {suggestions.suggestions.map((suggestion, index) => {
                  const suggestionKey = suggestionKeyFor(suggestions.generatedAt, suggestion, index);
                  const acceptedQuest = acceptedQuests[suggestionKey];

                  return (
                    <article
                      key={suggestionKey}
                      className="overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-[#131a25]"
                    >
                      <div className="flex flex-col gap-5 p-6 lg:flex-row lg:items-start lg:justify-between">
                        <div className="min-w-0 flex-1">
                          <div className="flex flex-wrap items-start gap-3">
                            <div className="min-w-0 flex-1">
                              <h3 className="text-2xl font-semibold tracking-tight text-slate-950 dark:text-slate-50">
                                {suggestion.title}
                              </h3>
                              <p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700 dark:text-slate-200">
                                {suggestion.description}
                              </p>
                            </div>

                            <span
                              className={`rounded-full border px-3 py-1 text-xs font-semibold capitalize ${difficultyTone(
                                suggestion.difficulty
                              )}`}
                            >
                              {suggestion.difficulty}
                            </span>
                          </div>

                          <div className="mt-4 flex flex-wrap items-center gap-2 text-xs">
                            <span className="rounded-full border border-slate-200 px-2.5 py-1 text-slate-600 dark:border-slate-700 dark:text-slate-300">
                              {suggestion.estimatedMinutes} min
                            </span>
                            <span className="rounded-full border border-slate-200 px-2.5 py-1 text-slate-600 dark:border-slate-700 dark:text-slate-300">
                              {categoryLabel(suggestion.category)}
                            </span>
                          </div>

                          <p className="mt-5 text-sm leading-6 text-slate-600 dark:text-slate-300">
                            {suggestion.reason}
                          </p>
                        </div>

                        <div className="w-full max-w-sm rounded-[24px] border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-[#0d131c]">
                          {acceptedQuest ? (
                            <div className="space-y-3">
                              <div className="text-xs font-semibold uppercase tracking-[0.22em] text-emerald-600 dark:text-emerald-300">
                                Accepted
                              </div>
                              <div className="text-sm text-slate-700 dark:text-slate-200">
                                This suggestion is now an active private quest.
                              </div>
                              <Link
                                to={`/quests/${acceptedQuest.questId}`}
                                className="inline-flex items-center gap-2 rounded-2xl bg-slate-950 px-4 py-2 text-sm font-medium text-white hover:bg-slate-800 dark:bg-slate-100 dark:text-slate-950 dark:hover:bg-white"
                              >
                                View quest
                                <ArrowUpRight className="h-4 w-4" />
                              </Link>
                            </div>
                          ) : (
                            <div className="space-y-3">
                              <div className="text-xs font-semibold uppercase tracking-[0.22em] text-slate-500 dark:text-slate-400">
                                Quest Actions
                              </div>
                              <button
                                onClick={() => openReviewForSuggestion(suggestion, index)}
                                className="w-full rounded-2xl bg-slate-950 px-4 py-2.5 text-sm font-medium text-white shadow-lg shadow-slate-950/15 hover:bg-slate-800 dark:bg-slate-100 dark:text-slate-950 dark:hover:bg-white"
                              >
                                Accept as Quest
                              </button>
                              <button
                                disabled
                                title="Save for Later is planned but not implemented yet."
                                className="flex w-full items-center justify-between rounded-2xl border border-slate-200 px-4 py-2.5 text-sm text-slate-500 opacity-70 dark:border-slate-700 dark:text-slate-400"
                              >
                                <span>Save for Later</span>
                                <span className="rounded-full border border-slate-200 px-2 py-0.5 text-[11px] dark:border-slate-700">
                                  Soon
                                </span>
                              </button>
                              <div className="text-xs leading-5 text-slate-500 dark:text-slate-400">
                                The created quest will start immediately, last 7 days, and default to private
                                visibility.
                              </div>
                            </div>
                          )}
                        </div>
                      </div>
                    </article>
                  );
                })}
              </div>
            ) : (
              <div className="rounded-[24px] border border-slate-200 bg-white p-6 text-sm text-slate-600 dark:border-slate-800 dark:bg-[#131a25] dark:text-slate-300">
                The coach returned a safe fallback without quest cards. You can try again at any time.
              </div>
            )}

            <div className="grid gap-4 lg:grid-cols-2">
              <section className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-[#131a25]">
                <div className="text-xs font-semibold uppercase tracking-[0.22em] text-slate-500 dark:text-slate-400">
                  Reflection
                </div>
                <p className="mt-3 text-sm leading-6 text-slate-700 dark:text-slate-200">{suggestions.reflection}</p>
              </section>

              <section className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-[#131a25]">
                <div className="text-xs font-semibold uppercase tracking-[0.22em] text-slate-500 dark:text-slate-400">
                  Streak-Saving Nudge
                </div>
                <p className="mt-3 text-sm leading-6 text-slate-700 dark:text-slate-200">{suggestions.nudge}</p>
              </section>
            </div>
          </>
        )}
      </section>

      <section
        ref={settingsRef}
        className="overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-[#131a25]"
      >
        <button
          onClick={() => setSettingsExpanded((current) => !current)}
          className="flex w-full items-center justify-between px-6 py-5 text-left"
        >
          <div>
            <div className="text-xs font-semibold uppercase tracking-[0.22em] text-slate-500 dark:text-slate-400">
              Privacy & AI Settings
            </div>
            <h2 className="mt-1 text-xl font-semibold text-slate-950 dark:text-slate-50">Coach settings</h2>
            <p className="mt-1 text-sm text-slate-600 dark:text-slate-300">
              Minimal quest context only. No uploads, proof media, or unrelated profile data are used.
            </p>
          </div>
          {settingsExpanded ? (
            <ChevronUp className="h-5 w-5 text-slate-500" />
          ) : (
            <ChevronDown className="h-5 w-5 text-slate-500" />
          )}
        </button>

        {settingsExpanded && (
          <div className="border-t border-slate-200 px-6 py-5 dark:border-slate-800">
            <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_260px]">
              <div className="space-y-5">
                <label className="flex items-start gap-3 rounded-[24px] border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-[#0d131c]">
                  <input
                    type="checkbox"
                    checked={draftOptIn}
                    onChange={(event) =>
                      setSettingsForm((current) => ({
                        ...current,
                        aiCoachEnabled: event.target.checked,
                      }))
                    }
                    className="mt-1 h-4 w-4 rounded border-slate-300 text-slate-900 focus:ring-slate-400"
                  />
                  <div>
                    <div className="text-sm font-medium text-slate-900 dark:text-slate-100">Enable AI Coach</div>
                    <div className="mt-1 text-xs text-slate-600 dark:text-slate-300">
                      Required before the coach can generate suggestions for your account.
                    </div>
                  </div>
                </label>

                <div>
                  <label className="block text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
                    Goal
                  </label>
                  <textarea
                    value={settingsForm.coachGoal ?? ""}
                    onChange={(event) =>
                      setSettingsForm((current) => ({
                        ...current,
                        coachGoal: event.target.value,
                      }))
                    }
                    rows={5}
                    placeholder="Example: Build speedrunning consistency with short, repeatable sessions that stay realistic after work."
                    className="mt-1 w-full rounded-[24px] border border-slate-200 bg-white px-4 py-3 text-sm leading-6 dark:border-slate-800 dark:bg-[#0d131c]"
                  />
                </div>
              </div>

              <div className="space-y-5">
                <label className="flex items-start gap-3 rounded-[24px] border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-[#0d131c]">
                  <input
                    type="checkbox"
                    checked={includeRecentHistory}
                    onChange={(event) => setIncludeRecentHistory(event.target.checked)}
                    className="mt-1 h-4 w-4 rounded border-slate-300 text-slate-900 focus:ring-slate-400"
                  />
                  <div>
                    <div className="text-sm font-medium text-slate-900 dark:text-slate-100">Use recent quest history</div>
                    <div className="mt-1 text-xs text-slate-600 dark:text-slate-300">
                      Lets the coach tighten suggestions using recent completion timestamps and quest titles.
                    </div>
                  </div>
                </label>

                <div className="rounded-[24px] border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600 dark:border-slate-800 dark:bg-[#0d131c] dark:text-slate-300">
                  <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.22em] text-slate-500 dark:text-slate-400">
                    <ShieldCheck className="h-4 w-4" />
                    Privacy notes
                  </div>
                  <ul className="mt-3 space-y-2 text-sm leading-6">
                    <li>Suggestions use only minimal quest context.</li>
                    <li>Proof uploads and raw media are excluded.</li>
                    <li>Server-side validation enforces the returned quest shape.</li>
                  </ul>
                </div>
              </div>
            </div>

            <div className="mt-5 flex flex-wrap items-center gap-3">
              <button
                onClick={onSaveSettings}
                disabled={saveSettingsM.isPending}
                className="rounded-2xl bg-slate-950 px-4 py-2 text-sm font-medium text-white shadow-lg shadow-slate-950/15 hover:bg-slate-800 disabled:opacity-60 dark:bg-slate-100 dark:text-slate-950 dark:hover:bg-white"
              >
                {saveSettingsM.isPending ? "Saving…" : "Save coach settings"}
              </button>

              {!persistedOptIn && (
                <span className="text-xs text-amber-700 dark:text-amber-300">
                  Enable AI Coach and save before generating suggestions.
                </span>
              )}
            </div>
          </div>
        )}
      </section>
    </div>
  );
}
